name: narrative-engine
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip>=23.0
  - numpy>=1.21.0
  - pip:
    - sentence-transformers>=2.2.0
    - anthropic>=0.5.0
    - python-dotenv>=0.19.0
    - rich>=10.0.0 